name: Test and deploy to heroku

on: 
  push: 
    branches: [main]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
      
    - name: Install dependencies
      run: yarn

    - name: Run build
      run: yarn build

    - name: Run e2e tests
      run: yarn test:e2e
    
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
      
    - name: Install dependencies
      run: yarn

    - name: Run build
      run: yarn build

    - name: Run e2e tests
      run: yarn test:unit

  deploy:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
      
    - name: Install dependencies
      run: yarn
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "tcc-backend-dunhao"
        heroku_email: "dunhaotcc@gmail.com"